name: Develop
on:
  push:
    branches:
      - develop
      - githubActionsRefactoring
jobs:
  # ==========================================================================
  # Create Github tag/release and export short SHA of current HEAD
  prepareRelease:
    runs-on: ubuntu-latest
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
      github_sha_short: ${{ steps.slug.outputs.sha8 }}
    steps:
      - name: Get short SHA
        id: slug
        run: echo "::set-output name=sha8::$(echo ${GITHUB_SHA} | cut -c1-8)"
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: build${{ github.run_number }}-${{ steps.slug.outputs.sha8 }}
          release_name: CI build ${{ github.run_number }}
          body: |
            Continuous integration build
            - This is build #${{ github.run_number }}
            - Lets see how it works :-)
          draft: false
          prerelease: true

  # ==========================================================================
  # Build all x86 Linux flavours
  buildLinux:
    runs-on: ubuntu-latest
    needs: prepareRelease
    strategy:
      matrix:
        distro: [ CentOS/Dockerfile, Debian/Dockerfile_Buster, Debian/Dockerfile_Stretch, Fedora/Dockerfile, OpenSUSE/Dockerfile, Ubuntu/Dockerfile_18_04, Ubuntu/Dockerfile_20_04 ]
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
      - name: Build docker images
        run: docker build -t local -f Docker/${{ matrix.distro }}_noUpload --build-arg BUILD_THREADS=2 .
        env:
          GITHUB_CI_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  # ==========================================================================
  # Build aarch64 version (Raspberry PI ARMv8)
  buildARM:
    runs-on: ubuntu-latest
    needs: prepareRelease
    strategy:
      matrix:
        distro: [ RaspberryPi/Dockerfile_Buster]
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
      - name: Set up QEMU
        id: qemu
        uses: docker/setup-qemu-action@v1
        with:
          image: tonistiigi/binfmt:latest
          platforms: arm64
      - name: Build docker images
        run: docker build -t local -f Docker/${{ matrix.distro }}_noUpload --build-arg BUILD_THREADS=2 .
        env:
          GITHUB_CI_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  # ==========================================================================
  # Build MacOS version
  buildMacOS:
    runs-on: macos-latest
    needs: prepareRelease
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
      - name: Install Qt
        uses: jurplel/install-qt-action@v2
        with:
          version: '5.12.10'
          setup-python: 'false'
          modules: 'qtwebengine'
      - name: Install dependencies
        run: |
          curl -L https://bintray.com/homebrew/bottles/download_file?file_path=boost-1.74.0.high_sierra.bottle.tar.gz -o boost-1.74.0.high_sierra.bottle.tar.gz
          brew install -f boost-1.74.0.high_sierra.bottle.tar.gz
          brew install berkeley-db@4
      - name: Build MacOS binaries
        run: ./scripts/cmake-build-mac.sh -g
        env:
          MAC_QT_DIR: ${{ env.Qt5_DIR }}
          BOOST_VERSION_MAC: 1.74.0
      - name: Upload MacOS Build
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.prepareRelease.outputs.upload_url }} # This pulls from the prepareRelease step before, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps
          asset_path: ${{ github.workspace }}/cmake-build-cmdline-mac/aliaswallet/Alias.dmg
          asset_name: Alias-build${{ github.run_number }}-${{ needs.prepareRelease.outputs.github_sha_short }}-Mac.dmg
          asset_content_type: application/octet-stream

  # ==========================================================================
  # Build Windows version
  buildWindows:
    runs-on: windows-latest
    needs: prepareRelease
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
      - name: Install Qt
        uses: jurplel/install-qt-action@v2
        with:
          version: '5.12.9'
          setup-python: 'false'
          modules: 'qtwebengine'
      - name: Install vcpkg and packages with cache
        uses: lukka/run-vcpkg@v6
        with:
          vcpkgArguments: 'berkeleydb boost leveldb openssl'
          vcpkgGitCommitId: a037d826492039db9d58af47a1e1248037d15f40
          vcpkgTriplet: x64-windows
      - name: Build Windows binaries
        run: ./scripts/cmake-build-win.bat
        env:
          VCPKG_DEFAULT_TRIPLET: x64-windows
          QTDIR: ${{ env.Qt5_Dir }}
          VSDIR: 'C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise'
          CMAKEDIR: 'C:\Program Files\CMake\bin'
          VCPKGDIR: ${{ github.workspace }}/vcpkg
      - name: Create zip archive
        uses: papeloto/action-zip@v1
        with:
          files: ${{ github.workspace }}/build/
          dest: ${{ github.workspace }}/Alias-${{ github.run_number }}-${{ needs.prepareRelease.outputs.github_sha_short }}-Win64-Qt5.12.zip.zip
      - name: Upload Windows Build
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.prepareRelease.outputs.upload_url }} # This pulls from the prepareRelease step before, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps
          asset_path: ${{ github.workspace }}/Alias-${{ github.run_number }}-${{ needs.prepareRelease.outputs.github_sha_short }}-Win64-Qt5.12.zip.zip
          asset_name: ${{ github.workspace }}/Alias-${{ github.run_number }}-${{ needs.prepareRelease.outputs.github_sha_short }}-Win64-Qt5.12.zip.zip
          asset_content_type: application/octet-stream

  # ==========================================================================
  # Dummy-Build A
  buildDummyA:
    runs-on: ubuntu-latest
    needs: prepareRelease
    steps:
      - uses: actions/checkout@v1
      - name: Run a one-line script
        run: echo Hello, world!
      - name: Run a multi-line script
        run: |
          echo Sleep 10s...
          sleep 10
          echo Now go ahead!
      - name: Upload Release
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.prepareRelease.outputs.upload_url }} # This pulls from the prepareRelease step before, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps
          asset_path: ${{ github.workspace }}/Alias-icon-colour-03.svg
          asset_name: Alias-Icon2.svg
          asset_content_type: application/octet-stream

  # ==========================================================================
  # Dummy-Build B
  buildDummyB:
    runs-on: ubuntu-latest
    needs: prepareRelease
    steps:
      - uses: actions/checkout@v1
      - name: Run a one-line script
        run: echo Hello, world!
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
      - name: Upload Release
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.prepareRelease.outputs.upload_url }} # This pulls from the prepareRelease step before, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps
          asset_path: ${{ github.workspace }}/Alias-icon-colour-03.svg
          asset_name: Alias-Icon.svg
          asset_content_type: application/octet-stream
